### ISSUE TITLE
메시지 전송이 정상적으로 이루어지지 않는 것 같습니다.

### ISSUE THREAD

**Issue by gdl-888** [kpjhg0124/zabgrass-discord#2]
환경: 윈도우 비스타 서비스팩2 32비트 / 파이썬 버전 3.7.3 / Discord.py '20년 6월 16일 버전

![image](https://user-images.githubusercontent.com/55873929/84790860-cd70e900-b02c-11ea-98d4-dbaae6bada6c.png)

봇에 메시지 전송 권한 부여는 하였습니다.

`ask_end`으로 끝나는 메시지를 전송했을 때 도스창에는 출력되나 보낸 메시지 채널에서 반응이 없습니다. 또한 `!zab`를 했을 때 `Client.send_message` 속성이 없다고 합니다.

5월 초에 윈도우 7 환경에서도 실행해보았으나 오류는 달랐으나 메시지를 디스코드 채널에 전송하지 않았습니다.

**Comment by kpjhg0124** [comment]
안녕하세요. 마지막 커밋 일자 이후에 Discord.py 모듈의 주요 API가 전반적으로 수정된 적이 있습니다.

목적도 기능도 코드 퀄리티도 저세상으로 날려버렸기 때문에 그냥 방치해놨던 것입니다. Discord 모듈을 학습할 목적이시라면 다른 레포를 참고하시는 것을 권장합니다.

감사합니다.
